name: Selenium Tests with Allure and Gmail Notification

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium and ChromeDriver (Ubuntu 24.04 compatible)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

      - name: Run tests with Pytest and generate Allure results
        run: |
          pytest --alluredir=allure-results

      - name: Zip Allure results
        run: zip -r allure-results.zip allure-results

      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Send Allure results via Gmail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Selenium Test Report - ${{ job.status }}
          body: |
            Hello Team,

            The Selenium test job finished with status: **${{ job.status }}**.
            Please find the attached Allure report archive.

            Regards,  
            GitHub Actions
          to: ${{ secrets.EMAIL_RECEIVER }}
          from: GitHub CI <${{ secrets.EMAIL_USERNAME }}>
          attachments: allure-results.zip
