name: Selenium Tests with Allure HTML + GitHub Pages + Email

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

      - name: Run Selenium tests with Allure results
        run: pytest --alluredir=allure-results

      - name: Download Allure CLI
        run: |
          curl -L -o allure.zip https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip -o allure.zip -d allure-cli
          chmod +x allure-cli/allure-2.27.0/bin/allure

      - name: Generate Allure HTML report
        run: |
          ./allure-cli/allure-2.27.0/bin/allure generate allure-results -o allure-report --clean
          mkdir -p docs/allure-report
          cp -r allure-report/* docs/allure-report/

      - name: Commit Allure report to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git add docs/
          git commit -m "Update Allure report [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main

      - name: Send email with report link via Gmail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Allure Report - ${{ job.status }}
          body: |
            Hello Team,

            ✅ The Selenium GitHub Action has completed with status: **${{ job.status }}**.

            📊 View the Allure Report:
            👉 https://bismaya2401.github.io/python-selanium/allure-report/index.html

            Regards,  
            GitHub CI
          to: ${{ secrets.EMAIL_RECEIVER }}
          from: GitHub CI <${{ secrets.EMAIL_USERNAME }}>
